#
# Configuration file for the core plugin
#


# Each world has an individual configuration file.
# Check out the "worlds" folder in the plugin's data folder.


# Worlds that have bloodmoons enabled.
# Reload the plugin, and a config file should generate for said worlds
#
# If you want to use this as a blacklist, set Whitelist false, and
# Replace WorldsList with commented.
#
# WorldsList: []
WorldsList:
  - world
# If true, the WorldsList will be used as a whitelist.
# If false, the WorldsList will be used as a blacklist.
# If used as a blacklist, all other worlds will have a bloodmoon config created and read. (Including new ones)
Whitelist: true