# If the world should have bloodmoons enabled.
enabled: true
# The effects that will be active when the bloodmoon is active.
# https://plugins.auxilor.io/effects/configuring-an-effect
effects:
  # Outgoing Damage (Player -> Entity)
  - triggers:
      - melee_attack
      - bow_attack
    filters:
      entities:
        - PLAYER
    mutators:
      - id: dispatcher_as_victim
    effects:
      - id: damage_multiplier
        args:
          multiplier: "0.2"
  # Incoming damage (Entity -> Player)
  - triggers:
      - melee_attack
      - bow_attack
    filters:
      entities:
        - ZOMBIE
        - SKELETON
        - PHANTOM
        - ZOMBIE
    mutators:
      - id: dispatcher_as_victim
    effects:
      - id: damage_multiplier
        args:
          multiplier: "2.0"
  - triggers:
      - entity_death
    effects:
      - id: smite
        args:
          damage: 1
conditions: [ ]
# Length of the bloodmoon in seconds.
Length: 360
# If the weather should be set to thunder during a bloodmoon.
SetThunder: true
# Bossbar settings.
Bossbar:
  BossbarTitle: "<red>Bloodmoon"
  Enabled: true
  Color: RED
  Style: PROGRESS
  Fog: true
  DarkenScreen: true
  # If true, the bossbar will increase with time
  # If false, the bossbar will decrease with time
  Increasing: true
# If bloodmoons should set do daylight cycle to false whenever a bloodmoon is active.
SetDaylightCycle: true
# Two options, "days" or "timed".
# If "days" is selected, the bloodmoon will activate every x days at night.
# If "timed" is selected, the bloodmoon will activate after a specific time and when the world is night.
# If "none", or anything else is selected, the bloodmoon will not activate on its own.
BloodmoonActivate: Days
# These two options only apply if BloodmoonActivate is set to their respective values.
# There is no built-in spigot method to check if a day has passed.
# To get around this the plugin checks every 5 ticks if it turned day or night. Then it counts based off that.
# This may not work correctly if you have a plugin that alters the rate of time.
Days: 5
# The time in seconds until the bloodmoon activates.
# Once the plugin detects that it is night, and the time has passed, the bloodmoon will activate.
Timed: 0
# If the prefix should be added to the message.
UsePrefix: true
Messages:
  Activation: "<red>A bloodmoon is upon us."
  Deactivation: "<green>Bloodmoon has ended."
# Commands to run on activation or deactivation.
# Do not add a "/" in front of the command.
# %world% will be replaced with the world name.
commands:
  activation: [ ]
  expiry: [ ]