# The effects that will be active when the bloodmoon is active.
# https://plugins.auxilor.io/effects/configuring-an-effect
effects:
  # Outgoing Damage (Player -> Entity)
  - triggers:
      - melee_attack
      - bow_attack
    filters:
      entities:
        - PLAYER
    mutators:
      - id: dispatcher_as_victim
    effects:
      - id: damage_multiplier
        args:
          multiplier: "0.2"
  # Incoming damage (Entity -> Player)
  - triggers:
      - melee_attack
      - bow_attack
    filters:
      entities:
        - ZOMBIE
        - SKELETON
        - PHANTOM
        - ZOMBIE
    mutators:
      - id: dispatcher_as_victim
    effects:
      - id: damage_multiplier
        args:
          multiplier: "2.0"
  - triggers:
      - entity_death
    effects:
      - id: smite
        args:
          damage: 1
conditions: [ ]
# Length of the bloodmoon in seconds.
length: 360
# Players may be able to skip the night by sleeping in a bed, if this is not enabled.
bed-disabled: true
# If the weather should be set to thunder during a bloodmoon.
set-thunder: true
# Bossbar settings.
bossbar:
  title: "<red>Bloodmoon"
  enabled: true
  # Available colors:
  # BLUE, GREEN, PINK, PURPLE, RED, WHITE and YELLOW
  color: RED
  # For more styles look here:
  # https://jd.advntr.dev/api/4.7.0/net/kyori/adventure/bossbar/BossBar.Overlay.html
  style: PROGRESS
  fog: true
  darken-screen: true
  # If true, the bossbar will increase with time
  # If false, the bossbar will decrease with time
  increasing: true
# If bloodmoons should set do daylight cycle to false whenever a bloodmoon is active.
# If this is not enabled, the day may shift during the bloodmoon.
stop-daylight-cycle: true
# Should the plugin play a victory chime when the bloodmoon ends?
victory-chime: true
# Should the plugin have a chance to play a sound every 20 seconds during the bloodmoon?
periodic-cave-sounds:
  enabled: true
  # 0.005 = 0.5% Chance to play.
  chance: 0.005
# If the bloodmoon shouldn't change the time of the world.
# This may break some BloodmoonActivate methods.
# This is useful if you have a plugin that changes the time of the world, or
# The bloodmoon is active in a dimension where time doesn't matter.
disable-time-change: false
on-player-death:
  clear-inventory: false
  clear-exp: false
  custom-death-message: false
messages:
  # If the prefix should be added to the message.
  use-prefix: false
  activation-enabled: true
  activation-announce-global: true
  # %world% = World name
  activation: "<red>A bloodmoon is upon us."
  deactivation-enabled: true
  deactivation-announce-global: true
  # %world% = World name
  deactivation: "<green>The Bloodmoon has ended."
  bed-deny-enabled: true
  bed-deny-message: "<red>You cannot sleep during a bloodmoon."
  # Death messages won't have a prefix added to them, even if UsePrefix is true.
  # %player% = Player's name
  # %player_displayname% = Player's display name
  death-message: "%player% couldn't handle the wrath of the bloodmoon"
# Commands to run on activation or deactivation.
# Do not add a "/" in front of the command.
# %world% will be replaced with the world name.
commands:
  activation: [ ]
  expiry: [ ]

# The method of activating the bloodmoon.
# If "days" is selected, the bloodmoon will activate every x days at night.
# If "timed" is selected, the bloodmoon will activate after a specific time and when the world is night.
# If "chance" is selected, the bloodmoon will activate after a random chance every night.
# If "mirror" is selected, the bloodmoon will activate shortly after another world's bloodmoon activates.
# If "none" is selected, the bloodmoon will not activate on its own, and must be activated manually.
activation-method: Days

#######################################################################################
#  These options only apply if BloodmoonActivate is set to their respective values.   #
#######################################################################################


# If BloodmoonActivate isn't set to "days", this section will be ignored.
days:
  # There is no built-in paper method to check if a day has passed.
  # To get around this the plugin checks every 5 ticks if the time jumped from day to night, then it counts based off that.
  # This may not work correctly if you have a plugin that alters the rate of time.
  count: 5

# If BloodmoonActivate isn't set to "timed", this section will be ignored.
timed:
  # The time in seconds until the bloodmoon activates.
  duration: 7200
  # If the bloodmoon should only activate at night if Timed is enabled.
  # This should be disabled if this is in the end or nether.
  night-only: true


# If BloodmoonActivate isn't set to "chance", this section will be ignored.
chance:
  # The max value is 1.0, which is 100%.
  # The initial chance of the bloodmoon activating.
  #   0.05 = 5%,   0.1 = 10%,   1.0 = 100%, etc.
  initial-percentage: 0.05
  increment:
    # Set true to increment the chance every night the bloodmoon doesn't activate.
    enabled: true
    # The max and min increment values. The plugin grabs a random value between these two numbers and adds it to the chance.
    min: 0.05
    max: 0.1


# If BloodmoonActivate isn't set to "mirror", this section will be ignored.
mirror:
  # The world to mirror the bloodmoon from, meaning if the bloodmoon is active in this world, it will activate in the mirrored world.
  # Reminder: THIS DOES NOT MIRROR THE CONFIG FILES OR THE LENGTH OF THE BLOODMOON.
  # Just copy and paste the config above the BloodmoonActivate line to do that.
  world: "world"

# If BloodmoonActivate isn't to "none", this will be ignored.
none:
  # If the bloodmoon should be active when the server starts.
  always-active: false
