name: ${pluginName}
version: ${version}
main: net.refractored.bloodmoonreloaded.BloodmoonPlugin
api-version: "1.21"
authors: [ refractored ]

dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false
